name: full_flutter_project
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # State management
  flutter_bloc: ^8.1.3
  # Code generation ( minly used with cubit & retrofit )
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  # Dependency injection
  get_it: ^7.6.4
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.5
  pretty_dio_logger: ^1.3.1
  # localization
  intl: ^0.18.1
  easy_localization: ^3.0.3
  # Shared preferences
  shared_preferences: ^2.2.2
  # Splash screen
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

